"""empty message

Revision ID: 72efbf01bf04
Revises: beb517796058
Create Date: 2018-06-13 12:22:52.625493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72efbf01bf04'
down_revision = 'beb517796058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('telephone', sa.String(length=11), nullable=False))
    op.create_unique_constraint(None, 'front_user', ['telephone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'front_user', type_='unique')
    op.drop_column('front_user', 'telephone')
    # ### end Alembic commands ###
